# Generated by Django 2.2.12 on 2020-05-20 08:48

from django.db import migrations
from authapp.models import ShopUser


def forwards_func(apps, schema_editor):
    #super_user_model = apps.get_model("authapp", "ShopUser")  # Load model for make changes
    ShopUser.objects.create_superuser('larce', 'larce@geekshop.local', 'larce', age=33)
    #super_user = super_user_model.objects.create(
        #pk=1,
        #username="larce", email='larce@geekshop.local', password='larce', is_superuser=True, age=33)


def reverse_func(apps, schema_editor):
    super_user_model = apps.get_model("authapp", "ShopUser")  # Load model for make changes

    # Delete all objects
    super_user_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("authapp", "0001_initial")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]